"""added story table and its relations with user

Revision ID: fc2568d6300b
Revises: f45fd9c627e8
Create Date: 2025-04-02 22:01:52.628423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc2568d6300b'
down_revision: Union[str, None] = 'f45fd9c627e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_seen_stories',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'story_id')
    )
    op.drop_index('ix_story_views_id', table_name='story_views')
    op.drop_index('ix_story_views_story_id', table_name='story_views')
    op.drop_index('ix_story_views_user_id', table_name='story_views')
    op.drop_table('story_views')
    op.drop_index('ix_followers_followed_id', table_name='followers')
    op.drop_index('ix_followers_follower_id', table_name='followers')
    op.drop_index('ix_followers_id', table_name='followers')
    op.drop_table('followers')
    op.drop_index('ix_liked_stories_id', table_name='liked_stories')
    op.drop_index('ix_liked_stories_story_id', table_name='liked_stories')
    op.drop_index('ix_liked_stories_user_id', table_name='liked_stories')
    op.drop_table('liked_stories')
    op.drop_column('stories', 'seen_by')
    op.add_column('users', sa.Column('fullname', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('users', sa.Column('birthday', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('profile_picture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_picture')
    op.drop_column('users', 'birthday')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'fullname')
    op.add_column('stories', sa.Column('seen_by', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_table('liked_stories',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('story_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name='liked_stories_story_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='liked_stories_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='liked_stories_pkey')
    )
    op.create_index('ix_liked_stories_user_id', 'liked_stories', ['user_id'], unique=False)
    op.create_index('ix_liked_stories_story_id', 'liked_stories', ['story_id'], unique=False)
    op.create_index('ix_liked_stories_id', 'liked_stories', ['id'], unique=False)
    op.create_table('followers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('follower_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('followed_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], name='followers_followed_id_fkey'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name='followers_follower_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='followers_pkey')
    )
    op.create_index('ix_followers_id', 'followers', ['id'], unique=False)
    op.create_index('ix_followers_follower_id', 'followers', ['follower_id'], unique=False)
    op.create_index('ix_followers_followed_id', 'followers', ['followed_id'], unique=False)
    op.create_table('story_views',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('story_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('viewed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name='story_views_story_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='story_views_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='story_views_pkey'),
    sa.UniqueConstraint('user_id', 'story_id', name='unique_user_story_view')
    )
    op.create_index('ix_story_views_user_id', 'story_views', ['user_id'], unique=False)
    op.create_index('ix_story_views_story_id', 'story_views', ['story_id'], unique=False)
    op.create_index('ix_story_views_id', 'story_views', ['id'], unique=False)
    op.drop_table('user_seen_stories')
    # ### end Alembic commands ###
